/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.xml.datatype.DatatypeFactory;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/**
 *
 * @author asus
 */
public class FormBooking extends javax.swing.JFrame {

    /**
     * Creates new form Booking
     */
    public FormBooking() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public ArrayList<String> restaurant;

    String strDataRestaurant;
    String strDataCustomer;
    LocalTime time;
    int jam, menit;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDatePickerUtil1 = new org.jdatepicker.util.JDatePickerUtil();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNamaRestoran = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        jSpinnerMejaDipesan = new javax.swing.JSpinner();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCek = new javax.swing.JButton();
        jSpinnerMenit = new javax.swing.JSpinner();
        jSpinnerJam = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerTersedia = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nama Restoran");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 142, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 86, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Tanggal Pemesanan");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 142, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah Meja yang Dipesan");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 180, 20));

        txtNamaRestoran.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtNamaRestoran.setEnabled(false);
        txtNamaRestoran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaRestoranActionPerformed(evt);
            }
        });
        getContentPane().add(txtNamaRestoran, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 37, 210, -1));

        txtAlamat.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtAlamat.setEnabled(false);
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 74, 210, -1));

        jSpinnerMejaDipesan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jSpinnerMejaDipesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 47, -1));

        jDateChooser1.setDateFormatString("yyyy-MM-dd");
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 111, 141, 22));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Jumlah Meja yang Tersedia");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 20));

        btnBook.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });
        getContentPane().add(btnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 90, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("a");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(99, 6, 169, -1));

        btnCek.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCek.setText("Cek");
        btnCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCekActionPerformed(evt);
            }
        });
        getContentPane().add(btnCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, 21));

        jSpinnerMenit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jSpinnerMenit, new org.netbeans.lib.awtextra.AbsoluteConstraints(221, 144, 53, -1));

        jSpinnerJam.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinnerJam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinnerJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 144, 47, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Jam Pemesanan");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 147, 142, -1));

        jSpinnerTersedia.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jSpinnerTersedia.setEnabled(false);
        getContentPane().add(jSpinnerTersedia, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 46, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/smallForm.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        strDataRestaurant = restaurant.get(0);

        btnBook.setEnabled(false);
        //Store Data
        String[] dataRes = strDataRestaurant.split("-");

        jLabel6.setText("Booking " + dataRes[2]);
        txtNamaRestoran.setText(dataRes[2]);
        txtAlamat.setText(dataRes[3]);
        int jamBuka = Integer.parseInt(dataRes[6].split(":")[0]);
        int menitBuka = Integer.parseInt(dataRes[6].split(":")[1]);
        int jamTutup = Integer.parseInt(dataRes[7].split(":")[0]);
        int menitTutup = Integer.parseInt(dataRes[7].split(":")[1]);
        SpinnerNumberModel model = new SpinnerNumberModel(jamBuka, jamBuka, jamTutup, 1);
        jSpinnerJam.setModel(model);


    }//GEN-LAST:event_formWindowOpened

    private void txtNamaRestoranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaRestoranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaRestoranActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:
        try {
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = jDateChooser1.getDate();
            String strDate = date.format(tanggal);
            System.out.println(strDate);

            com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
            com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();

            /*
            GregorianCalendar gc = new GregorianCalendar();
            gc.setTime(tanggal);
            XMLGregorianCalendar date2 = DatatypeFactory.newInstance().newXMLGregorianCalendar(gc);
             */
            int jumlahMejaDipesan = (int) jSpinnerMejaDipesan.getValue();

            //Time
            if (jumlahMejaDipesan > (int) jSpinnerTersedia.getValue()) {
                JOptionPane.showMessageDialog(this, "Maaf Meja sudah Penuh.Coba cek di hari atau jam yang lainnya");
            } else {
                int dialog = JOptionPane.showConfirmDialog(null,
                        "Apakah Anda Ingin Melakukan Pesanan Pre Order Makanan Pada Restoran ?",
                        "Pesan Informasi",
                        JOptionPane.YES_NO_OPTION);

                if (dialog == JOptionPane.YES_OPTION) {
                    FormPreOrder form = new FormPreOrder();
                    form.rest = strDataRestaurant;
                    form.linkBooking = strDataRestaurant + "!!" + strDataCustomer + "!!" + strDate + "!!" + jumlahMejaDipesan + "!!" + time.toString();
                    form.setVisible(true);
                } else {
                    String hasil = port.tambahBooking(strDataCustomer, strDataRestaurant, strDate, jumlahMejaDipesan, time.toString());
                    System.out.println(strDataCustomer);
                    System.out.println(strDataRestaurant);
                    System.out.println(jumlahMejaDipesan);
                    System.out.println(time.toString());
                    if (hasil.equals("Benar")) {
                        JOptionPane.showMessageDialog(this, "Selamat Pemesanan Anda Berhasil");
                    } else {
                        JOptionPane.showMessageDialog(this, "Maaf ");
                    }
                    this.dispose();
                }

            }

        } catch (Exception ex) {

        }
    }//GEN-LAST:event_btnBookActionPerformed

    private void btnCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCekActionPerformed
        // TODO add your handling code here:
        try {
            com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
            com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();

            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date tanggal = jDateChooser1.getDate();
            String strDate = date.format(tanggal);
            System.out.println(strDate);
            //Time
            jam = (int) jSpinnerJam.getValue();
            menit = (int) jSpinnerMenit.getValue();
            time = LocalTime.of(jam, menit);

            int hasil = port.jumlahMejaBerdasarkanTanggal(strDate, (strDataRestaurant.split("-")[0]), time.toString());
            int tersedia = Integer.parseInt(strDataRestaurant.split("-")[8]) - hasil;

            String check = port.checkBook(strDataRestaurant, strDataCustomer, strDate,time.toString());
            if (check.equals("Benar")) {

                jSpinnerTersedia.setValue(tersedia);
                btnBook.setEnabled(true);
            }
            else{
                JOptionPane.showMessageDialog(this, "Maaf Anda Sudah Booking pada Hari ini");
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnCekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBook;
    private javax.swing.JButton btnCek;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private org.jdatepicker.util.JDatePickerUtil jDatePickerUtil1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSpinner jSpinnerJam;
    private javax.swing.JSpinner jSpinnerMejaDipesan;
    private javax.swing.JSpinner jSpinnerMenit;
    private javax.swing.JSpinner jSpinnerTersedia;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNamaRestoran;
    // End of variables declaration//GEN-END:variables
}
