/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author asus
 */
public class FormPreOrder extends javax.swing.JFrame {

    /**
     * Creates new form FormPreOrder
     */
    String rest;
    String linkBooking;
    ArrayList<String> menuPilihan = new ArrayList<>();
    ArrayList<String> lmasakan = new ArrayList<>();
    ArrayList<String> jum = new ArrayList<>();
    ArrayList<String> lharga= new ArrayList<>();

    public FormPreOrder() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tableMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        cbMenu = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        jSpinnerJumlah = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btnTambah = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableMenu.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nama Menu", "Jumlah"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMenuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableMenu);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 187, 340, 150));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Pre Order");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 90, 30));

        btnSimpan.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 110, -1));

        cbMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbMenu.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbMenuItemStateChanged(evt);
            }
        });
        getContentPane().add(cbMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 240, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Nama Menu");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 54, 78, 20));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Harga");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 37, 20));

        txtHarga.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtHarga.setEnabled(false);
        getContentPane().add(txtHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 240, -1));

        jSpinnerJumlah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        getContentPane().add(jSpinnerJumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 72, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, 20));

        btnTambah.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 150, 120, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/smallForm.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public int cek(ArrayList<String> x, String m) {
        int j = 0;
        for (int i = 0; i < x.size(); i++) {
            String data = x.get(i);
            if (data == m) {
                j = i;
            }
        }
        return j;

    }

    public void tambah(ArrayList<String> listMenu,ArrayList<String> hasil,ArrayList<String> x,ArrayList<String> y,ArrayList<String> z){
        for (int i=0;i<x.size();i++){
            String dataX=x.get(i);
            String dataY=y.get(i);
            String dataZ=z.get(i);
            hasil.add(index(listMenu,dataX)+";"+dataX+";"+dataY+";"+dataZ);
        }
    }

    public int index(ArrayList<String> list,String masakan){
        int j=0;
        for (int i=0;i<list.size();i++){
            String[] hasil=list.get(i).split("-");
            if (hasil[1].equals(masakan)){
                j=Integer.parseInt(hasil[0]);
            }
        }
        return j;
    }
    private void tableMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMenuMouseClicked

    }//GEN-LAST:event_tableMenuMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        try {
            com.ubaya.projectdistprog.MenuWS_Service service = new com.ubaya.projectdistprog.MenuWS_Service();
            com.ubaya.projectdistprog.MenuWS port = service.getMenuWSPort();

            ArrayList<String> listMenu = (ArrayList<String>) port.displayMenuRestoran(rest.split("-")[0]);
            menuPilihan= new ArrayList<>();
            String masakan = (String) cbMenu.getSelectedItem();
            int jumlah = (int) jSpinnerJumlah.getValue();
            if (lmasakan.contains(masakan)) {
                int c = cek(lmasakan, masakan);
                jum.set(c, String.valueOf(Integer.parseInt(jum.get(c)) + jumlah));
            } else {
                lmasakan.add(masakan);
                jum.add(String.valueOf(jumlah));
                lharga.add(txtHarga.getText());
            }
            tambah(listMenu,menuPilihan,lmasakan,jum,lharga);
            DefaultTableModel model = (DefaultTableModel) tableMenu.getModel();

            model.setRowCount(0);
            for (int i = 0; i < menuPilihan.size(); i++) {
                Object[] data = {
                    menuPilihan.get(i).split(";")[1], menuPilihan.get(i).split(";")[2]
                };
                model.addRow(data);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
            com.ubaya.projectdistprog.MenuWS_Service service = new com.ubaya.projectdistprog.MenuWS_Service();
            com.ubaya.projectdistprog.MenuWS port = service.getMenuWSPort();

            ArrayList<String> hasil = (ArrayList<String>) port.displayMenuRestoran(rest.split("-")[0]);
            for (int i = 0; i < hasil.size(); i++) {
                cbMenu.addItem(hasil.get(i).split("-")[1]);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void cbMenuItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbMenuItemStateChanged
        // TODO add your handling code here:
        try {
            String cari = (String) cbMenu.getSelectedItem();
            com.ubaya.projectdistprog.MenuWS_Service service = new com.ubaya.projectdistprog.MenuWS_Service();
            com.ubaya.projectdistprog.MenuWS port = service.getMenuWSPort();

            ArrayList<String> hasil = (ArrayList<String>) port.displayMenuRestoran(rest.split("-")[0]);
            for (int i = 0; i < hasil.size(); i++) {
                String[] data = hasil.get(i).split("-");
                if (data[1].equals(cari)) {
                    txtHarga.setText(data[2]);
                    break;
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_cbMenuItemStateChanged

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
        try {
            com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
            com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();
            
            String[] dataBooking=linkBooking.split("!!");
            port.tambahBookingPreOrder(dataBooking[0],dataBooking[1], dataBooking[2], Integer.parseInt(dataBooking[3]), dataBooking[4], menuPilihan);
            JOptionPane.showMessageDialog(this, "Selamat Pesanan Anda dan Pre Order Telahh Berhasil");
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPreOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPreOrder().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerJumlah;
    private javax.swing.JTable tableMenu;
    private javax.swing.JTextField txtHarga;
    // End of variables declaration//GEN-END:variables
}
