/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.table.*;

/**
 *
 * @author asus
 */
public class MainCustomer extends javax.swing.JFrame {

    /**
     * Creates new form MainCustomer
     */
    String kustomer;
    public MainCustomer() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableBooking = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        HistoryPemesananCustomer = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableBooking.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama Restoran", "Alamat", "Nomor Telepon", "Jumlah Meja yang Tersedia", "Jam Buka", "Jam Tutup"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBooking);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 627, 269));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Booking Restaurant");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 180, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Cari berdasarkan :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 110, 20));

        cbCari.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Restoran", "Alamat" }));
        getContentPane().add(cbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 130, -1));

        txtCari.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 50, 370, -1));

        HistoryPemesananCustomer.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        HistoryPemesananCustomer.setText("History Pemesanan");
        HistoryPemesananCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryPemesananCustomerActionPerformed(evt);
            }
        });
        getContentPane().add(HistoryPemesananCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 150, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/table.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        //WebService
        com.ubaya.projectdistprog.RestaurantWS_Service service = new com.ubaya.projectdistprog.RestaurantWS_Service();
        com.ubaya.projectdistprog.RestaurantWS port = service.getRestaurantWSPort();
        DefaultTableModel model = (DefaultTableModel) tableBooking.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[7];

        ArrayList<String> listModel = (ArrayList<String>) port.displayRes();
        for (int i = 0; i < listModel.size(); i++) {
            String[] data = listModel.get(i).split("-");
            
            rowData[0]=data[0];
            rowData[1] = data[2];
            rowData[2] = data[3];
            rowData[3] = data[4];
            rowData[4] = data[8];
            rowData[5] = data[6];
            rowData[6] = data[7];
            model.addRow(rowData);
        }

    }//GEN-LAST:event_formWindowOpened

    private void tableBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookingMouseClicked
        // TODO add your handling code here:
        try {
            int baris = tableBooking.getSelectedRow();
            TableModel model = tableBooking.getModel();
            String id = (model.getValueAt(baris, 0).toString());
            System.out.println(id);
            
            com.ubaya.projectdistprog.RestaurantWS_Service service = new com.ubaya.projectdistprog.RestaurantWS_Service();
            com.ubaya.projectdistprog.RestaurantWS port = service.getRestaurantWSPort();
            
            ArrayList<String> cek=(ArrayList<String>) port.ambilDataById(id);
            
            String[] data = port.ambilDataById(id).get(0).split("-");
            int dialog = JOptionPane.showConfirmDialog(null,
                    "Apakah Anda Ingin Melakukan Pesanan Pada Restoran " + data[2] + " ?",
                    "Pesan Informasi",
                    JOptionPane.YES_NO_OPTION);

            if (dialog == JOptionPane.YES_OPTION) {
                FormBooking book= new FormBooking();
                book.strDataCustomer=kustomer;
                book.restaurant=cek;
                book.setVisible(true);
            } 
        } catch (Exception Ex) {
            JOptionPane.showMessageDialog(this, Ex.getMessage());
        }
    }//GEN-LAST:event_tableBookingMouseClicked

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        try {
            String selected = "";
            switch (cbCari.getSelectedItem().toString()) {
                case "Nama Restoran":
                    selected = "nama_restoran";
                    break;
                case "Alamat":
                    selected = "alamat";
                    break;
                default:
                    selected="tidak";
                    break;
            }

            System.out.println(selected);
            com.ubaya.projectdistprog.RestaurantWS_Service service = new com.ubaya.projectdistprog.RestaurantWS_Service();
            com.ubaya.projectdistprog.RestaurantWS port = service.getRestaurantWSPort();
            DefaultTableModel model = (DefaultTableModel) tableBooking.getModel();
            model.setRowCount(0);
            Object[] rowData = new Object[7];

            ArrayList<String> listModel = (ArrayList<String>) port.displayResCari(selected, txtCari.getText());
            for (int i = 0; i < listModel.size(); i++) {
            String[] data = listModel.get(i).split("-");
            rowData[0]=data[0];
            rowData[1] = data[2];
            rowData[2] = data[3];
            rowData[3] = data[4];
            rowData[4] = data[8];
            rowData[5] = data[6];
            rowData[6] = data[7];
            model.addRow(rowData);
        }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void HistoryPemesananCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryPemesananCustomerActionPerformed
        // TODO add your handling code here:
        HistoryPemesananCustomer formHistory= new HistoryPemesananCustomer();
        formHistory.c=kustomer;
        formHistory.setVisible(true);
        
    }//GEN-LAST:event_HistoryPemesananCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HistoryPemesananCustomer;
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBooking;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
