/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author asus
 */
public class MainRestoran extends javax.swing.JFrame {

    /**
     * Creates new form MainRestoran
     */
    public ArrayList<String> restoran;

    public MainRestoran() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBooking = new javax.swing.JTable();
        btnTambahMenu = new javax.swing.JButton();
        btnShowMenu = new javax.swing.JButton();
        btnHistory = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel1.setText("Booking Report");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 150, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Cari berdasarkan :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 44, 110, -1));

        cbCari.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nama Pelanggan" }));
        getContentPane().add(cbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 41, 150, -1));

        txtCari.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariKeyReleased(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 41, 370, -1));

        tableBooking.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        tableBooking.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Nama Pelanggan", "Tanggal Pemesanan", "Jam Pemesanan", "Jumlah Meja yang Dipesan", "Keterangan", "PreOrder"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBooking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBookingMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBooking);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 66, 641, 280));

        btnTambahMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnTambahMenu.setText("Tambah Menu");
        btnTambahMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambahMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btnShowMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnShowMenu.setText("Show Menu");
        btnShowMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnShowMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, -1, -1));

        btnHistory.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnHistory.setText("History Pemesanan Customer");
        btnHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoryActionPerformed(evt);
            }
        });
        getContentPane().add(btnHistory, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/table.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void RefreshTable() {
        com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
        com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();

        DefaultTableModel model = (DefaultTableModel) tableBooking.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[7];

        String restoranku = restoran.get(0);
        String[] dataResKu = restoranku.split("-");
        ArrayList<String> listModel = (ArrayList<String>) port.displayBookingRestaurant(dataResKu[0], "tidak", "");

        for (int i = 0; i < listModel.size(); i++) {
            String[] data = listModel.get(i).split(";");
            String x = "Tidak";
            rowData[0] = data[0];
            rowData[1] = data[13];
            rowData[2] = data[2];
            rowData[3] = data[4];
            rowData[4] = data[1];
            rowData[5] = data[3];
            String[] datamakan = listModel.get(i).split("!makan!");
            if (datamakan.length == 2) {
                x = "Ada";
            }
            rowData[6] = x;

            model.addRow(rowData);

        }
    }

    private void txtCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyReleased
        // TODO add your handling code here:
        try {
            String selected = "";
            switch (cbCari.getSelectedItem().toString()) {
                case "Nama Pelanggan":
                    selected = "c.nama_customer";
                    break;
                case "Tanggal":
                    selected = "b.tanggal_pemesanan";
                    break;
                default:
                    selected = "tidak";
                    break;
            }

            System.out.println(selected);

            com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
            com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();

            DefaultTableModel model = (DefaultTableModel) tableBooking.getModel();
            model.setRowCount(0);
            Object[] rowData = new Object[7];
            String restoranku = restoran.get(0);
            String[] dataResKu = restoranku.split("-");
            ArrayList<String> listModel = (ArrayList<String>) port.displayBookingRestaurant(dataResKu[0], selected, txtCari.getText());
            for (int i = 0; i < listModel.size(); i++) {
                String[] data = listModel.get(i).split(";");
                String x = "Tidak";
                rowData[0] = data[0];
                rowData[1] = data[13];
                rowData[2] = data[2];
                rowData[3] = data[4];
                rowData[4] = data[1];
                rowData[5] = data[3];
                String[] datamakan = listModel.get(i).split("!makan!");
                if (datamakan.length == 2) {
                    x = "Ada";
                }
                rowData[6] = x;
                model.addRow(rowData);

            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_txtCariKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        try {
        com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
        com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();

        DefaultTableModel model = (DefaultTableModel) tableBooking.getModel();
        model.setRowCount(0);
        Object[] rowData = new Object[7];

        String restoranku = restoran.get(0);
        String[] dataResKu = restoranku.split("-");
        ArrayList<String> listModel = (ArrayList<String>) port.displayBookingRestaurant(dataResKu[0], "tidak", "");

        for (int i = 0; i < listModel.size(); i++) {
            String[] data = listModel.get(i).split(";");
            String x = "Tidak";
            rowData[0] = data[0];
            rowData[1] = data[13];
            rowData[2] = data[2];
            rowData[3] = data[4];
            rowData[4] = data[2];
            rowData[5] = data[3];
            String[] datamakan = listModel.get(i).split("!makan!");
            if (datamakan.length == 2) {
                x = "Ada";
            }
            rowData[6] = x;

            model.addRow(rowData);

        }
        } catch (Exception e) {
            System.out.println("Error di form load restoran");
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void tableBookingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBookingMouseClicked
        // TODO add your handling code here:
        try {
            int baris = tableBooking.getSelectedRow();
            TableModel model = tableBooking.getModel();
            String id = (model.getValueAt(baris, 0).toString());
            String keterangan = (model.getValueAt(baris, 5).toString());
            String cekPo = (model.getValueAt(baris, 6).toString());
            System.out.println(cekPo);
            if (cekPo.equals("Tidak")) {
                if (keterangan.equals("sudahpesan")) {
                    int dialog = JOptionPane.showConfirmDialog(null,
                            "Apakah Tamu Sudah Datang ?",
                            "Pesan Informasi",
                            JOptionPane.YES_NO_OPTION);

                    if (dialog == JOptionPane.YES_OPTION) {
                        com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
                        com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();
                        port.updateKeteranganBooking(id);
                        RefreshTable();
                    }
                } else if (keterangan.equals("sudahdatang")) {
                    int dialog = JOptionPane.showConfirmDialog(null,
                            "Apakah Tamu Sudah Selesai ?",
                            "Pesan Informasi",
                            JOptionPane.YES_NO_OPTION);

                    if (dialog == JOptionPane.YES_OPTION) {
                        com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
                        com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();
                        port.updateKeteranganBooking(id);
                        RefreshTable();
                    }
                }
            } else {
                if (keterangan.equals("sudahpesan")) {
                    int dialog = JOptionPane.showConfirmDialog(null,
                            "Apakah ingin melihat Pre Order ?",
                            "Pesan Informasi",
                            JOptionPane.YES_NO_OPTION);

                    if (dialog == JOptionPane.YES_OPTION) {
                        FormLihatPO formLihat = new FormLihatPO();
                        formLihat.restoranP = restoran.get(0);
                        formLihat.bookingId=id;
                        formLihat.setVisible(true);
                    }
                } else if (keterangan.equals("sudahdatang")) {
                    com.ubaya.projectdistprog.BookingWS_Service service = new com.ubaya.projectdistprog.BookingWS_Service();
                    com.ubaya.projectdistprog.BookingWS port = service.getBookingWSPort();
                    port.updateKeteranganBooking(id);
                    RefreshTable();
                }

            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_tableBookingMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void btnTambahMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahMenuActionPerformed
        // TODO add your handling code here:
        try{
            FormTambahMenu form1= new FormTambahMenu();
            form1.booking=restoran.get(0);
            form1.setVisible(true);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnTambahMenuActionPerformed

    private void btnShowMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMenuActionPerformed
        // TODO add your handling code here:
        try{
            FormShowMenu form1= new FormShowMenu();
            form1.rest=restoran.get(0);
            form1.setVisible(true);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnShowMenuActionPerformed

    private void btnHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoryActionPerformed
        // TODO add your handling code here:
        try{
            HistoryRestoran form1= new HistoryRestoran();
            form1.rest=restoran.get(0);
            form1.setVisible(true);
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_btnHistoryActionPerformed

    public void jButtonAction(java.awt.event.WindowEvent evt) {
        formWindowOpened(evt);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainRestoran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHistory;
    private javax.swing.JButton btnShowMenu;
    private javax.swing.JButton btnTambahMenu;
    private javax.swing.JComboBox<String> cbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableBooking;
    public javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
