/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import java.io.BufferedReader;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.Socket;
import java.time.LocalTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author asus
 */
public class RegisterRestoran extends javax.swing.JFrame {

    public RegisterRestoran() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        btnRegister = new javax.swing.JButton();
        txtNamaPemilik = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtNamaRestoran = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAlamat = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtNomor = new javax.swing.JTextField();
        jSpinnerJumlahMeja = new javax.swing.JSpinner();
        jSpinnerJam = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinnerMenit = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinnerMenitTutup = new javax.swing.JSpinner();
        jSpinnerJamTutup = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtPassRe = new javax.swing.JPasswordField();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel5.setText("Nama Pemilik:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 110, -1));

        btnRegister.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 200, 37));

        txtNamaPemilik.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtNamaPemilik, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 270, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Nama Restoran:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 130, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, 90, 20));

        txtNamaRestoran.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtNamaRestoran, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 270, -1));

        jLabel6.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel6.setText("REGISTER");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 150, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Alamat:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, 70, 20));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Password:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 90, 30));

        txtAlamat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 270, -1));

        txtUsername.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 270, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Re-type Password:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 150, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel9.setText("Jumlah Meja :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 110, 20));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel10.setText("Nomor Telepon :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 130, 20));

        txtNomor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtNomor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, 270, -1));

        jSpinnerJumlahMeja.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jSpinnerJumlahMeja, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 49, -1));

        jSpinnerJam.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSpinnerJam.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinnerJam, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 49, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel11.setText("Jam Buka :");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 90, 20));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setText(":");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 280, 5, -1));

        jSpinnerMenit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jSpinnerMenit, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 53, -1));

        jLabel13.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel13.setText(":");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 5, -1));

        jSpinnerMenitTutup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(jSpinnerMenitTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 53, -1));

        jSpinnerJamTutup.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jSpinnerJamTutup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jSpinnerJamTutup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 47, -1));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Jam Tutup :");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 100, -1));

        txtPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 270, -1));

        txtPassRe.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txtPassRe, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 410, 270, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/form.png"))); // NOI18N
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        try {
            com.ubaya.projectdistprog.RestaurantWS_Service service = new com.ubaya.projectdistprog.RestaurantWS_Service();
            com.ubaya.projectdistprog.RestaurantWS port = service.getRestaurantWSPort();

            Socket s = new Socket("localhost", 65432);
            BufferedReader msgFromServer = new BufferedReader(new InputStreamReader(s.getInputStream()));
            DataOutputStream msgToServer = new DataOutputStream(new DataOutputStream(s.getOutputStream()));

            //Input
            String nama_pemilik = txtNamaPemilik.getText();
            String nama_restoran = txtNamaRestoran.getText();
            String alamat = txtAlamat.getText();
            String nomor = txtNomor.getText();
            String username = txtUsername.getText();
            String pass = new String(txtPassword.getPassword());
            String re_pass = new String(txtPassRe.getPassword());
            int jumlah_meja = (int) jSpinnerJumlahMeja.getValue();
            int jamBuka = (int) jSpinnerJam.getValue();
            int menitBuka = (int) jSpinnerMenit.getValue();
            int jamTutup = (int) jSpinnerJamTutup.getValue();
            int menitTutup = (int) jSpinnerMenitTutup.getValue();

            LocalTime timeBuka = LocalTime.of(jamBuka, menitBuka);
            LocalTime timeTutup = LocalTime.of(jamTutup, menitTutup);
            System.out.println(timeBuka);

            //Server Check Register
            msgToServer.writeBytes("REGISTERRESTAURANT;" + nama_pemilik + ";" + nama_restoran + ";" + alamat + ";" + nomor + ";" + username + ";" + pass + ";" + jumlah_meja + ";" + timeBuka.toString() + ";" + timeTutup.toString() + "\n");
            //Hasil WS
            String hasilCheck = msgFromServer.readLine();

            if (pass.equals(re_pass)) {
                if (hasilCheck.equals("Berhasil")) {
                    JOptionPane.showMessageDialog(this, "Selamat Registrasi Restoran " + nama_restoran + " Berhasil");
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Maaf Username Sudah Ada. Silahkan Coba Username Lainnya");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Maaf Password Anda Tidak Sesuai");
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterRestoran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new RegisterRestoran().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(RegisterRestoran.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSpinner jSpinnerJam;
    private javax.swing.JSpinner jSpinnerJamTutup;
    private javax.swing.JSpinner jSpinnerJumlahMeja;
    private javax.swing.JSpinner jSpinnerMenit;
    private javax.swing.JSpinner jSpinnerMenitTutup;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtNamaPemilik;
    private javax.swing.JTextField txtNamaRestoran;
    private javax.swing.JTextField txtNomor;
    private javax.swing.JPasswordField txtPassRe;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables

}
